### ISSUE TITLE
Composer 2 support

### ISSUE THREAD

**Issue by dingo-d** [TypistTech/imposter-plugin#329]
I see that the `composer-plugin-api` is set to `1.1`, meaning we cannot use it with [v2](https://blog.packagist.com/composer-2-0-is-now-available/) of the Composer.

Any plans to make it compatible with it? Is there some way to help make it compatible?

### Edit

I've forked it and added 

```json
        "composer-plugin-api": "^1.1 || ^2",
```

To the required field, and all the tests passed 🤷‍♂️

**Comment by iruzevic** [comment]
Any updates on this issue?

**Comment by shmidtelson** [comment]
+1 I am waiting support composer 2

**Comment by shmidtelson** [comment]
https://github.com/TypistTech/imposter-plugin/pull/335 Main issue is here

**Comment by TangRufus** [comment]
Composer v2 support added in #339 
0.6.1 has been released.
Thank you all!
