### ISSUE TITLE
 [ErrorException] array_merge() expects at least 1 parameter, 0 given 

### ISSUE THREAD

**Issue by wujekbogdan** [TypistTech/imposter-plugin#43]
I'm getting the following error after running `composer imposter:run`

> [ErrorException]                                     
>  array_merge() expects at least 1 parameter, 0 given 

My `composer.json` file:

``` json
{
 // ...
  "require": {
    "composer/installers": "~1.0",
    "timber/timber": "^1.5",
    "abraham/twitteroauth": "^0.7.4",
    "defuse/php-encryption": "^2.1",
    "guzzlehttp/guzzle": "^6.3",
    "brain/cortex": "~1.0.0@dev",
    "symfony/var-dumper": "^4.2.0",
    "monolog/monolog": "^1.24.0",
    "google/cloud-firestore": "^1.0.0",
    "typisttech/imposter-plugin": "^0.3.1"
  },
  "autoload": {
    "psr-4": {
      "Sw\\": "lib/Sw/"
    },
    "files": [
        // some files here
    ]
  },
  "extra": {
    "imposter": {
      "namespace": "Sw\\Vendor"
    }
  }
}
```

**Comment by TangRufus** [comment]
Can you show the full console output and the `composer.lock` file?

I want to see which line / package cause the error

**Comment by cambell-prince** [comment]
I had this error also, the exception was in ArrayUtil::flatten.  Adding some extra protection around the $array fixed it for me.  Seems to be a catch 22 when the autoload hasn't been generated for the first time.

```php
    public static function flatten(array $array): array
    {
        if ($array === null) {
            return $array;
        }
        if (count($array) == 0) {
            return $array;
        }
        return call_user_func_array('array_merge', $array);
    }
```

**Comment by TangRufus** [comment]
related: https://github.com/TypistTech/imposter-plugin/issues/34

**Comment by TangRufus** [comment]
https://github.com/TypistTech/imposter/pull/85 silencely turn missing `autoload` into an empty array.

No warning is yelded. PRs are welcomed.

Re-open this issue if the problem presists.
